### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by FoamyGuy** [jposada202020/Adafruit_CircuitPython_Styles#4]
I tried this library out a bit on my PyPortal tonight. 

I think it might be good to have functions inside of this library responsible for styling other widgets. 

For testing I added this function into `__init__.py`: 
```
def style_label(target_label, style):
    target_label.color = get_hex(THEME[style]["TEXT"])
    target_label.background_color = get_hex(THEME[style]["BACKGROUND"])
```
This way everything needed is contained within this library instead of needing any changes inside of label.

I think we could provide similar functions for other widgets as well. So it may be worth changing the `"TEXT"` property to `"FOREGROUND"` or something else more generic like that. 

Last thing is I think it would be nice if these styles were broken out into seperate dictionary objects instead of one big one. Something like:
```
DarkTeal12 = {
    "BACKGROUND": "#004a7c",
    "FOREGROUND": "#fafafa"
}
LightBrown13 = {
    "BACKGROUND": "#ebf5ee",
    "FOREGROUND": "#921224"
}
#...
```
this way user code can import it like:
```
from adafruit_styles.styles import LightBrown13
```
So that they just get the one theme they want instead of having all of them loaded to memory.

**Comment by jposada202020** [comment]
@FoamyGuy Yes I really like your idea of importing only the style.  That will take into account our memory limitations and we can use the colors across the widgets, The original library contains other definitions, for example for border, and widget background, and so on, the is used in the library because the ones are you mentioned are already there, I work on making ten styles with all the characteristics, that could apply to our widgets. And agree, the color library normally is used ``alone`` or is called when you setup a new color in your class. So I like very much your idea.
I am guessing that you are proposing to add the helper function inside __init__ of adafruit.display_text right?

So I propose next steps:
1. Work on makin 10 complete color styles taking into account your comments (Division, and Names)
2. Select widget library as a test ground
3. Include the def styles function in the __init__
4. Test and verify
5. Include the rest of the colors and some color functions that I have in my scripts and that others that I saw kmatch using as well, in __init__ maybe.
6. and I think after we could include in the main.

Let me know your thoughts. Thanks for reviewing :)

**Comment by FoamyGuy** [comment]
I think the `style_label()` function should go inside of `__init__.py` in this library. `adafruit_styles/__init.py`

**Comment by jposada202020** [comment]
| Widget       | Background Color | Text Color  | Border | Line Color    | Tick Color                             | Others                                                            |
| ------------ | ---------------- | ----------- | ------ | ------------- | -------------------------------------- | ----------------------------------------------------------------- |
| Annotation   | X                | X           | X      |               |                                        |
| Cartesian    | X                | X           |        | X             | X                                      | pointer                                                           |
| Dial         | X                | label\_font | needle | X             | value                                  |
| Equalizer    | X                |             | X      |               |                                        |                                                                   |
| Flipinput    |                  | X           |        | arrow outline | arrow                                  |
| Slider       | X                | X           |        |               | X                                      |                                                                   |
| Switch       |                  |             |        |               |                                        | left, right, background on/off, fill, outline, background outline |
| Label        | X                | X           |        |               |                                        |                                                                   |
| Progress Bar |                  |             |        |               | bar\_color, fill\_color, outline color |
| Button       |                  | X           | X      |               |                                        | fill\_color                                                       |

**Comment by jposada202020** [comment]
Two differents uses:

## For widgets without color setter moehtod
```python
import board
import displayio
from adafruit_displayio_layout.widgets.annotation import Annotation
from adafruit_styles.styles import BluePurple

display = board.DISPLAY

switch_annotation = Annotation(
    widget=my_switch, 
    text="WappQ~",
    text_color=BluePurple["TEXT"],
    line_color=BluePurple["LINE_COLOR"],
)

my_group = displayio.Group(max_size=4)
my_group.append(switch_annotation)
display.show(my_group)

while True:
    pass
```

## For widgets with set color method or other update method
```python
import displayio
import board
from adafruit_display_text import bitmap_label
from adafruit_bitmap_font import bitmap_font
from Adafruit_CircuitPython_Styles import apply_style
from Adafruit_CircuitPython_Styles.styles import DarkAmber
display = board.DISPLAY

splash = displayio.Group(max_size=3)
MEDIUM_FONT = bitmap_font.load_font("../fonts/LibreBodoniv2002-Bold-10.bdf")

text = "CircuitPython"
text_area = bitmap_label.Label(MEDIUM_FONT,
                        text=text,
                        x=155,
                        y=155,)
apply_style(text_area, DarkAmber)
splash.append(text_area)

display.show(splash)
while True:
    pass
```

**Comment by jposada202020** [comment]
New changes include documentation. and improvement in applying the style to the libraries where color set is not easily accesible via a setter.

this could be done by
```python
from adafruit_styles.style import GetStyle, BluePurple
colors = GetStyle(BluePurple)
```
attributes of the dictionary will be available under ``colors.text_color`` for example.

**Comment by FoamyGuy** [comment]
I think all of the things mentioned in this issue have been handled. Closing for now. Great work @jposada202020!
