### ISSUE TITLE
Example script needs small update

### ISSUE THREAD

**Issue by FoamyGuy** [jposada202020/Adafruit_CircuitPython_Styles#8]
The example script is still trying to do the old way where the styles were in a dictionary. It needs updated with these lines for the current version: 

```
from adafruit_styles.styles import DarkBlue
# ...
apply_style(text_area, DarkBlue)
```

**Comment by jposada202020** [comment]
@FoamyGuy thanks for the testing and reviewing, but just for the record, I followed your recommendation, they are still dics, just individual for each colorset. I corrected the example and tested it. 
![image](https://user-images.githubusercontent.com/34255413/113644989-029a0680-9654-11eb-91ce-9cdbbea4999e.png)
How e move this from here to Adafruit, I am not familiar with that process?!

**Comment by FoamyGuy** [comment]
Thanks for the fix @jposada202020. 

For adding to the Adafruit Bundle the process is similar to adding to the Community Bundle. Here is the repo for it: https://github.com/adafruit/Adafruit_CircuitPython_Bundle. To get a new library added we make a PR on that repo. The steps from here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-in-the-community-bundle are mostly the same for the Adafruit Bundle and the Community Bundle, the different repos are the main difference.
